### ISSUE TITLE
Logout does not work

### ISSUE THREAD

**Issue by cygery** [postfixadmin/postfixadmin#130]
Steps to reproduce:
- Login (either as admin or user)
- Click on the "logout" link which opens the corresponding "login.php" page
- User is still logged in (shown in footer and able to simply open "main.php" again)

Expected behavior:
- User is logged out, i.e., session is invalidated

Version affected:
- Master (tested with 220f828)

Please let me know if I can provide any further info.

**Comment by DavidGoodwin** [comment]
problem confirmed...

**Comment by DavidGoodwin** [comment]
possibly fixed in master; can you ```git pull``` or equivalent and retry?

thanks!

**Comment by cygery** [comment]
Partly fixed. Logout works now for admins. Logout still doesn't work for users.

**Comment by DavidGoodwin** [comment]
Ah, I never login as a user ..... :)

Thanks for the pull request; that's merged.
